### ISSUE TITLE
Groom IDE  사용 추천 ^^

### ISSUE THREAD

**Issue by riyenas0925** [haseungwon/haseungwon.github.io#1]
@haseungwon  구름 IDE에 node.js 빈프로젝트로 만들고 여기서 포스팅 하면 네이버 블로그 글쓰기 급은 아니여도 편하게 쓸수 있다 이말이야~ 참고할수있도록

**Comment by riyenas0925** [comment]
@haseungwon 아니 지금 보니까 jekyll 써서 블로그 만들었네;;; 
hexo(node.js)나 gatsby(react.js) 사용 하지 이시국에 ruby로 만들어진 jekyll를 쓴다고?????

**Comment by haseungwon** [comment]
??? 일본거임?

나의 iPhone에서 보냄

2019. 12. 23. 오후 10:05, Dongmin Kang <notifications@github.com> 작성:

**Comment by riyenas0925** [comment]
근데 살면서 써볼일 없는 루비보다는 node.js나 react로 만들어 ㅋㅋ

**Comment by haseungwon** [comment]
근데 ruby 생각보다 겁나게 편함 ㅌㅋㅋㅋ 함 다른걸로 해볼겡 ㅌㅋㅋㅋ

나의 iPhone에서 보냄

2019. 12. 25. 오전 8:27, Dongmin Kang <notifications@github.com> 작성:
